spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/dental_app
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: dentist
    password: dentist
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 7k2wF71Dj3oOW01VnTb06HH8cI88Ls3JEDd9A9ivKYc=
      expiration: 86400000 # 1 jour
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
    from: m.razi0363@gmail.com
server:
  port: 8088
